ValAddress = ""
OrcSeeds = [""]

[CosmosConfig]
    ChainID = "test"
    CustodialAddr = ""
    Denom = "stake"
    GRPCAddr = ""
    RPCAddr = ""
    AccountPrefix = "cosmos"
    GasAdjustment = 1.0
    GasPrice = "0.025stake"
    CoinType = 118

[NativeConfig]
    ChainID = "test"
    Denom = "stake"
    RPCAddr = ""
    GRPCAddr = ""
    AccountPrefix = "persistence"
    GasAdjustment = 1.0
    GasPrices = "0.025stake"
    CoinType = 118