# Note that any updates to this files will not be applied in CI
# until this file is merged into main. This is due to oddities of the labeller Github Action.
"C:app-wiring":
  - app/*.go
  - app/ante/**/*
  - app/**/*
  - cmd/**/**/*
  - cmd/**/*
  # Also match any module.go update
  - x/**/module.go

"C:x/liquidstakeibc":
  - x/liquidstakeibc/**/*
"T:build":
  - Makefile
  - Dockerfile
  - scripts/*
  - docker/**
"T:CI":
  - .github/**/*.yml
  - .golangci.yml
  - contrib/**
"C:CLI":
  - x/*/client/**/*
# Add "C:docs" label to documented related files and directories.
"C:docs":
  - bug.md
  - issue.md
  - proto-docs.md
  - README.md
  - x/**/*.md
  - x/**/*/*.md
  - tests/**/*.md