version: "2"

run:
  tests: false

linters:
  default: none
  enable:
    - errcheck         # unchecked errors
    - govet            # catches suspicious code constructs
    - staticcheck      # advanced correctness checks
    - misspell         # catch typos
    - ineffassign      # detect inefficient assignments
    - unused           # unused variables, funcs, types
  settings:
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports
