ValAddress = ""

OrcSeeds = [""]

[Cosmos]
    ChainID = ""
    CustodialAddr = ""
    Denom = ""
    RPCAddr = ""
    AccountPrefix = ""
    GasAdjustment    = 1.0
    GasPrice         = "0.025stake"
    CoinType         = 118

[Native]
    ChainID       = "test1"
    Denom         = "stake"
    RPCAddr       = ""
    GRPCAddr      = ""
    AccountPrefix = "cosmos"
    GasAdjustment = 1.0
    GasPrice      = "0.025stake"
    CoinType      = 118



