// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pstake/liquidstakeibc/v1beta1/liquidstakeibc.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HostChain struct {
	// host chain id
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// ibc connection id
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// protocol token denom
	LocalDenom string `protobuf:"bytes,3,opt,name=local_denom,json=localDenom,proto3" json:"local_denom,omitempty"`
	// native token denom
	HostDenom string `protobuf:"bytes,4,opt,name=host_denom,json=hostDenom,proto3" json:"host_denom,omitempty"`
	// minimum ls amount
	MinimumDeposit github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=minimum_deposit,json=minimumDeposit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"minimum_deposit"`
	// redemption rate
	CValue github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=c_value,json=cValue,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"c_value"`
}

func (m *HostChain) Reset()         { *m = HostChain{} }
func (m *HostChain) String() string { return proto.CompactTextString(m) }
func (*HostChain) ProtoMessage()    {}
func (*HostChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9a61e676043b6, []int{0}
}
func (m *HostChain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HostChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HostChain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HostChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostChain.Merge(m, src)
}
func (m *HostChain) XXX_Size() int {
	return m.Size()
}
func (m *HostChain) XXX_DiscardUnknown() {
	xxx_messageInfo_HostChain.DiscardUnknown(m)
}

var xxx_messageInfo_HostChain proto.InternalMessageInfo

func (m *HostChain) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *HostChain) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *HostChain) GetLocalDenom() string {
	if m != nil {
		return m.LocalDenom
	}
	return ""
}

func (m *HostChain) GetHostDenom() string {
	if m != nil {
		return m.HostDenom
	}
	return ""
}

type KVUpdate struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *KVUpdate) Reset()         { *m = KVUpdate{} }
func (m *KVUpdate) String() string { return proto.CompactTextString(m) }
func (*KVUpdate) ProtoMessage()    {}
func (*KVUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9a61e676043b6, []int{1}
}
func (m *KVUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KVUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KVUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KVUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVUpdate.Merge(m, src)
}
func (m *KVUpdate) XXX_Size() int {
	return m.Size()
}
func (m *KVUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_KVUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_KVUpdate proto.InternalMessageInfo

func (m *KVUpdate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVUpdate) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*HostChain)(nil), "pstake.liquidstakeibc.v1beta1.HostChain")
	proto.RegisterType((*KVUpdate)(nil), "pstake.liquidstakeibc.v1beta1.KVUpdate")
}

func init() {
	proto.RegisterFile("pstake/liquidstakeibc/v1beta1/liquidstakeibc.proto", fileDescriptor_71a9a61e676043b6)
}

var fileDescriptor_71a9a61e676043b6 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcb, 0xee, 0xd2, 0x40,
	0x14, 0xc6, 0xdb, 0xff, 0x85, 0x3f, 0x8c, 0xd7, 0x4c, 0x58, 0x14, 0x12, 0x5a, 0x83, 0x89, 0x71,
	0x43, 0x1b, 0x70, 0x67, 0xdc, 0x88, 0x5d, 0xd8, 0xb8, 0x30, 0x21, 0x81, 0x85, 0x2e, 0x9a, 0x76,
	0xe6, 0x04, 0x26, 0xb4, 0x33, 0x95, 0x99, 0x36, 0xf2, 0x16, 0x2e, 0x5d, 0xfa, 0x10, 0x3e, 0x04,
	0x3b, 0x89, 0x2b, 0xe3, 0x82, 0x18, 0x78, 0x11, 0xd3, 0x99, 0x26, 0x12, 0x76, 0xae, 0xfa, 0x9d,
	0xef, 0x77, 0xce, 0xd7, 0xb9, 0xa1, 0x49, 0x21, 0x55, 0xb2, 0x86, 0x20, 0x63, 0x9f, 0x4a, 0x46,
	0xb5, 0x66, 0x29, 0x09, 0xaa, 0x71, 0x0a, 0x2a, 0x19, 0x5f, 0xd8, 0x7e, 0xb1, 0x11, 0x4a, 0xe0,
	0x81, 0x99, 0xf1, 0x2f, 0x60, 0x33, 0xd3, 0xef, 0x2e, 0xc5, 0x52, 0xe8, 0xce, 0xa0, 0x56, 0x66,
	0xa8, 0xdf, 0x23, 0x42, 0xe6, 0x42, 0xc6, 0x06, 0x98, 0xc2, 0xa0, 0xe1, 0x8f, 0x2b, 0xd4, 0x79,
	0x2b, 0xa4, 0x7a, 0xb3, 0x4a, 0x18, 0xc7, 0x3d, 0xd4, 0x26, 0xb5, 0x88, 0x19, 0x75, 0xec, 0x27,
	0xf6, 0xf3, 0xce, 0xec, 0x4e, 0xd7, 0x11, 0xc5, 0x4f, 0xd1, 0x03, 0x22, 0x38, 0x07, 0xa2, 0x98,
	0xd0, 0xfc, 0x4a, 0xf3, 0xfb, 0xff, 0xcc, 0x88, 0x62, 0x0f, 0xdd, 0xcb, 0x04, 0x49, 0xb2, 0x98,
	0x02, 0x17, 0xb9, 0x73, 0xad, 0x5b, 0x90, 0xb6, 0xc2, 0xda, 0xc1, 0x03, 0x84, 0x56, 0x42, 0xaa,
	0x86, 0xdf, 0x68, 0xde, 0xa9, 0x1d, 0x83, 0x01, 0x3d, 0xca, 0x19, 0x67, 0x79, 0x99, 0xc7, 0x14,
	0x0a, 0x21, 0x99, 0x72, 0x6e, 0xeb, 0x9e, 0xe9, 0xab, 0xdd, 0xc1, 0xb3, 0x7e, 0x1f, 0xbc, 0x67,
	0x4b, 0xa6, 0x56, 0x65, 0xea, 0x13, 0x91, 0x37, 0xfb, 0x68, 0x3e, 0x23, 0x49, 0xd7, 0x81, 0xda,
	0x16, 0x20, 0xfd, 0x88, 0xab, 0x9f, 0xdf, 0x47, 0xa8, 0xd9, 0x66, 0xc4, 0xd5, 0xec, 0x61, 0x13,
	0x1a, 0x9a, 0x4c, 0x3c, 0x47, 0x77, 0x24, 0xae, 0x92, 0xac, 0x04, 0xa7, 0xf5, 0xdf, 0xf1, 0x21,
	0x90, 0xb3, 0xf8, 0x10, 0xc8, 0xac, 0x45, 0x16, 0x75, 0xd6, 0xcb, 0x9b, 0xaf, 0xdf, 0x3c, 0x7b,
	0x38, 0x41, 0xed, 0x77, 0x8b, 0x79, 0x41, 0x13, 0x05, 0xf8, 0x31, 0xba, 0x5e, 0xc3, 0xb6, 0x39,
	0xca, 0x5a, 0xe2, 0x2e, 0xba, 0x35, 0x3f, 0x36, 0xc7, 0x67, 0x8a, 0xe9, 0xc7, 0xdd, 0xd1, 0xb5,
	0xf7, 0x47, 0xd7, 0xfe, 0x73, 0x74, 0xed, 0x2f, 0x27, 0xd7, 0xda, 0x9f, 0x5c, 0xeb, 0xd7, 0xc9,
	0xb5, 0x3e, 0xbc, 0x3e, 0x5b, 0x51, 0x01, 0x1b, 0xc9, 0xa4, 0x02, 0x4e, 0xe0, 0x3d, 0x87, 0xc0,
	0xbc, 0x84, 0x11, 0x4f, 0x14, 0xab, 0x20, 0xa8, 0x26, 0xc1, 0xe7, 0xcb, 0x97, 0xa4, 0x17, 0x9c,
	0xb6, 0xf4, 0x4d, 0xbf, 0xf8, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x79, 0x00, 0x43, 0x63, 0x6f, 0x02,
	0x00, 0x00,
}

func (m *HostChain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HostChain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HostChain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.CValue.Size()
		i -= size
		if _, err := m.CValue.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstakeibc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.MinimumDeposit.Size()
		i -= size
		if _, err := m.MinimumDeposit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstakeibc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.HostDenom) > 0 {
		i -= len(m.HostDenom)
		copy(dAtA[i:], m.HostDenom)
		i = encodeVarintLiquidstakeibc(dAtA, i, uint64(len(m.HostDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LocalDenom) > 0 {
		i -= len(m.LocalDenom)
		copy(dAtA[i:], m.LocalDenom)
		i = encodeVarintLiquidstakeibc(dAtA, i, uint64(len(m.LocalDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintLiquidstakeibc(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintLiquidstakeibc(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KVUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KVUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KVUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintLiquidstakeibc(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintLiquidstakeibc(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLiquidstakeibc(dAtA []byte, offset int, v uint64) int {
	offset -= sovLiquidstakeibc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HostChain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovLiquidstakeibc(uint64(l))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovLiquidstakeibc(uint64(l))
	}
	l = len(m.LocalDenom)
	if l > 0 {
		n += 1 + l + sovLiquidstakeibc(uint64(l))
	}
	l = len(m.HostDenom)
	if l > 0 {
		n += 1 + l + sovLiquidstakeibc(uint64(l))
	}
	l = m.MinimumDeposit.Size()
	n += 1 + l + sovLiquidstakeibc(uint64(l))
	l = m.CValue.Size()
	n += 1 + l + sovLiquidstakeibc(uint64(l))
	return n
}

func (m *KVUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovLiquidstakeibc(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovLiquidstakeibc(uint64(l))
	}
	return n
}

func sovLiquidstakeibc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLiquidstakeibc(x uint64) (n int) {
	return sovLiquidstakeibc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HostChain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidstakeibc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HostChain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HostChain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstakeibc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstakeibc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocalDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstakeibc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LocalDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstakeibc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumDeposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstakeibc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumDeposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstakeibc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidstakeibc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KVUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidstakeibc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KVUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KVUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstakeibc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstakeibc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidstakeibc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidstakeibc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLiquidstakeibc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLiquidstakeibc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidstakeibc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidstakeibc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLiquidstakeibc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLiquidstakeibc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLiquidstakeibc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLiquidstakeibc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLiquidstakeibc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLiquidstakeibc = fmt.Errorf("proto: unexpected end of group")
)
