ValAddress = "persistencevaloper16e0p4vwufmsn0lucwsnfmjfx67ry84y4had58e"
OrcSeeds = ["soft brown armed regret hip few ancient control steel bright basic swamp sentence present immune napkin orbit giggle year another crowd essence noble dice"]

[CosmosConfig]
  ChainID = "gaiad"
  CustodialAddr = "cosmos15ddw7dkp56zytf3peshxr8fwn5w76y4g462ql2"
  Denom = "stake"
  GRPCAddr = "gaia-genesis.dev-native.svc.cluster.local:9090"
  RPCAddr = "http://gaia-genesis.dev-native.svc.cluster.local:26657"
  AccountPrefix = "cosmos"
  GasAdjustment = 1.5
  GasPrice = "0.025stake"
  CoinType = 118

[NativeConfig]
  ChainID = "pstaked"
  Denom = "stake"
  RPCAddr = "http://pstake-genesis.dev-native.svc.cluster.local:26657"
  GRPCAddr = "pstake-genesis.dev-native.svc.cluster.local:9090"
  AccountPrefix = "persistence"
  GasAdjustment = 1.5
  GasPrices = "0.025stake"
  CoinType = 118
