namespace: dev-native

resources:
- relayer.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: test-relayer-config
    files:
      - configs/config.toml
      - configs/keys.json
